version: '3.9'

services:
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    volumes:
      - .:/api

  # broker:
  #   build:
  #     context: ./broker
  #     dockerfile: Dockerfile
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     CELERY_RESULT_BACKEND: redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   volumes: ['./broker:/broker']

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    volumes:
      - .:/users

  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    volumes:
      - .:/tasks

volumes:
  pgdata: {}