version: '3.9'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/api

  # broker:
  #   build:
  #     context: ./broker
  #     dockerfile: Dockerfile
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     CELERY_RESULT_BACKEND: redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   volumes: ['./broker:/broker']

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - .:/users

  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    volumes:
      - .:/tasks

volumes:
  pgdata: {}