version: '3'

services:
  postgres:
    image: postgres:13
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: flask_celery
      POSTGRES_USER: flask_celery
      POSTGRES_PASSWORD: flask_celery
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - .:/api

  # broker:
  #   build:
  #     context: ./broker
  #     dockerfile: Dockerfile
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     CELERY_RESULT_BACKEND: redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   volumes: ['./broker:/broker']

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/users

volumes:
  pgdata:
  users: