version: '3.9'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/api

  files:
    build:
      context: ./files
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-credentials
      - BUCKET_NAME=miso-cloud-development
      - PROJECT_ID=proyecto-cloud-computing-miso
      - CONVERT_SUBSCRIPTION_ID=convert-subscription
    secrets:
      - gcp-credentials
    volumes: ['./files:/files']

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - .:/users

  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-credentials
      - PROJECT_ID=proyecto-cloud-computing-miso
      - UPLOAD_TOPIC_ID=upload-topic
      - CONVERT_TOPIC_ID=convert-topic
      - DOWNLOAD_TOPIC_ID=download-topic
    secrets:
      - gcp-credentials
    volumes:
      - .:/tasks

secrets:
  gcp-credentials:
    file: /home/victor/projects/proyecto-cloud-computing-miso-1d889a810e05.json