version: '3.9'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/api

  files:
    build:
      context: ./files
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes: ['./files:/files']

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - .:/users

  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    volumes:
      - .:/tasks

volumes:
  pgdata: {}